// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkffNX8zbJCMZNlQ_RhQdrxsvo_aspj0',
    appId: '1:653828792922:web:45c6f3d026dd74d12e2e63',
    messagingSenderId: '653828792922',
    projectId: 'zevent-33dd3',
    authDomain: 'zevent-33dd3.firebaseapp.com',
    databaseURL: 'https://zevent-33dd3.firebaseio.com',
    storageBucket: 'zevent-33dd3.appspot.com',
    measurementId: 'G-34525FGWNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NDpFt0rAXk5oP9idQk7ScVmpqOS4zJA',
    appId: '1:653828792922:android:6cc14e6876e4529f2e2e63',
    messagingSenderId: '653828792922',
    projectId: 'zevent-33dd3',
    databaseURL: 'https://zevent-33dd3.firebaseio.com',
    storageBucket: 'zevent-33dd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_03OPQ7USeLPAD_h0D6p78Rl7N_GDkg',
    appId: '1:653828792922:ios:7beb17ee3a370f992e2e63',
    messagingSenderId: '653828792922',
    projectId: 'zevent-33dd3',
    databaseURL: 'https://zevent-33dd3.firebaseio.com',
    storageBucket: 'zevent-33dd3.appspot.com',
    iosClientId: '653828792922-ldnh8kavulj0fr874u7q59muh0h0iiva.apps.googleusercontent.com',
    iosBundleId: 'xyz.thebad.zevent.zevent',
  );
}
